CREATE TABLE "varit_folder" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "varit_folder_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" varchar(255) NOT NULL,
	"parentId" integer,
	"s3Path" varchar(1024) NOT NULL,
	"createdAt" timestamp with time zone NOT NULL
);
--> statement-breakpoint
CREATE TABLE "varit_media_item" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "varit_media_item_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"fileName" varchar(512) NOT NULL,
	"originalName" varchar(512) NOT NULL,
	"mimeType" varchar(128) NOT NULL,
	"fileSize" integer NOT NULL,
	"s3Key" varchar(1024) NOT NULL,
	"s3Url" varchar(2048) NOT NULL,
	"folderId" integer,
	"note" text,
	"sendDate" date,
	"sent" boolean DEFAULT false NOT NULL,
	"createdAt" timestamp with time zone NOT NULL,
	"updatedAt" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "varit_study_card" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "varit_study_card_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"title" varchar(255) NOT NULL,
	"description" text NOT NULL,
	"youtubeUrl" varchar(1024),
	"imageUrl" varchar(2048),
	"imageS3Key" varchar(1024),
	"category" varchar(100),
	"difficulty" varchar(20) DEFAULT 'medium',
	"tags" text,
	"isCompleted" boolean DEFAULT false NOT NULL,
	"rating" integer DEFAULT 0,
	"notes" text,
	"createdAt" timestamp with time zone NOT NULL,
	"updatedAt" timestamp with time zone
);
--> statement-breakpoint
ALTER TABLE "varit_media_item" ADD CONSTRAINT "varit_media_item_folderId_varit_folder_id_fk" FOREIGN KEY ("folderId") REFERENCES "public"."varit_folder"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "folder_parent_idx" ON "varit_folder" USING btree ("parentId");--> statement-breakpoint
CREATE INDEX "folder_name_idx" ON "varit_folder" USING btree ("name");--> statement-breakpoint
CREATE INDEX "media_folder_idx" ON "varit_media_item" USING btree ("folderId");--> statement-breakpoint
CREATE INDEX "media_send_date_idx" ON "varit_media_item" USING btree ("sendDate");--> statement-breakpoint
CREATE INDEX "media_sent_idx" ON "varit_media_item" USING btree ("sent");--> statement-breakpoint
CREATE INDEX "media_created_idx" ON "varit_media_item" USING btree ("createdAt");--> statement-breakpoint
CREATE INDEX "study_card_category_idx" ON "varit_study_card" USING btree ("category");--> statement-breakpoint
CREATE INDEX "study_card_difficulty_idx" ON "varit_study_card" USING btree ("difficulty");--> statement-breakpoint
CREATE INDEX "study_card_completed_idx" ON "varit_study_card" USING btree ("isCompleted");--> statement-breakpoint
CREATE INDEX "study_card_created_idx" ON "varit_study_card" USING btree ("createdAt");--> statement-breakpoint
CREATE INDEX "study_card_rating_idx" ON "varit_study_card" USING btree ("rating");